import { fromZonedTime } from 'date-fns-tz'
import { appTimeZone } from '@/constants/date'
import { JobEntry } from '@/types/job'

const jobEntries: JobEntry[] = [
  {
    id: 'badalSeniorSoftwareEngineer',
    companyId: 'badal',
    companyName: 'Badal.io',
    title: 'Senior Software Engineer',
    location: 'Toronto, Ontario, Canada · Remote',
    startDate: fromZonedTime('2024-12-16', appTimeZone),
    endDate: undefined,
    skills: []
  },
  {
    id: 'badalStaffSoftwareEngineer',
    companyId: 'badal',
    companyName: 'Badal.io',
    title: 'Staff Software Engineer',
    location: 'Toronto, Ontario, Canada · Remote',
    startDate: fromZonedTime('2023-05-01', appTimeZone),
    endDate: fromZonedTime('2024-11-08', appTimeZone),
    skills: [
      'Docker',
      'Node.js',
      'I18n',
      'Express.js',
      'Monorepo',
      'Sales Engineering',
      'React.js',
      'Serverless Computing',
      'TypeScript',
      'Software Estimation',
      'Coaching & Mentoring',
      'Team Leadership',
      'Composable Headless',
      'React Native',
      'Media Management',
      'Solution Architecture',
      'Application Architecture',
      'Figma',
      'Next.js'
    ]
  },
  {
    id: 'quantumMobStaffSoftwareEngineer',
    companyId: 'quantumMob',
    companyName: 'Quantum Mob',
    title: 'Staff Software Engineer',
    location: 'Toronto, Ontario, Canada · Hybrid',
    startDate: fromZonedTime('2022-11-01', appTimeZone),
    endDate: fromZonedTime('2023-05-01', appTimeZone),
    skills: [
      'Docker',
      'Node.js',
      'I18n',
      'Express.js',
      'Monorepo',
      'Sales Engineering',
      'React.js',
      'Serverless Computing',
      'TypeScript',
      'Software Estimation',
      'Coaching & Mentoring',
      'Team Leadership',
      'Composable Headless',
      'React Native',
      'Media Management',
      'Solution Architecture',
      'Application Architecture',
      'Figma',
      'Next.js'
    ]
  },
  {
    id: 'quantumMobSeniorSoftwareEngineer',
    companyId: 'quantumMob',
    companyName: 'Quantum Mob',
    title: 'Senior Software Engineer',
    location: 'Toronto, Ontario, Canada',
    startDate: fromZonedTime('2021-11-01', appTimeZone),
    endDate: fromZonedTime('2022-10-01', appTimeZone),
    skills: [
      'Docker',
      'Node.js',
      'I18n',
      'Express.js',
      'Monorepo',
      'CI/CD',
      'PWAs',
      'React Testing Library',
      'React.js',
      'Serverless Computing',
      'React Query',
      'OAuth',
      'AODA',
      'TypeScript',
      'Software Estimation',
      'Coaching & Mentoring',
      'WCAG',
      'Team Leadership',
      'JavaScript',
      'Jest',
      'Redux.js',
      'Composable Headless',
      'React Native',
      'Media Management',
      'Application Architecture',
      'Figma',
      'Next.js'
    ]
  },
  {
    id: 'quantumMobSoftwareEngineerII',
    companyId: 'quantumMob',
    companyName: 'Quantum Mob',
    title: 'Software Engineer II',
    location: 'Toronto, Canada Area',
    startDate: fromZonedTime('2020-11-01', appTimeZone),
    endDate: fromZonedTime('2021-10-01', appTimeZone),
    skills: [
      'Docker',
      'Node.js',
      'I18n',
      'Express.js',
      'Monorepo',
      'CI/CD',
      'PWAs',
      'React Testing Library',
      'React.js',
      'Serverless Computing',
      'Webpack',
      'React Query',
      'OAuth',
      'AODA',
      'TypeScript',
      'Software Estimation',
      'Coaching & Mentoring',
      'WCAG',
      'Team Leadership',
      'JavaScript',
      'Jest',
      'PostgreSQL',
      'MySQL',
      'Redux.js',
      'ORM',
      'React Native',
      'Media Management',
      'Application Architecture',
      'Figma',
      'Next.js'
    ]
  },
  {
    id: 'quantumMobSoftwareEngineerI',
    companyId: 'quantumMob',
    companyName: 'Quantum Mob',
    title: 'Software Engineer I',
    location: 'Toronto, Ontario, Canada',
    startDate: fromZonedTime('2019-11-01', appTimeZone),
    endDate: fromZonedTime('2020-10-01', appTimeZone),
    skills: [
      'Docker',
      'Node.js',
      'I18n',
      'Express.js',
      'Monorepo',
      'CI/CD',
      'React.js',
      'Webpack',
      'TypeScript',
      'JavaScript',
      'PostgreSQL',
      'MySQL',
      'Redux.js',
      'ORM',
      'Figma',
      'Next.js'
    ]
  },
  {
    id: 'brandfireIntermediateFrontEndDeveloper',
    companyId: 'brandfire',
    companyName: 'Brandfire Marketing Group Inc.',
    title: 'Intermediate Front End Developer',
    location: 'Markham, Ontario',
    startDate: fromZonedTime('2017-04-01', appTimeZone),
    endDate: fromZonedTime('2019-11-01', appTimeZone),
    skills: [
      'Node.js',
      'I18n',
      'Express.js',
      'CI/CD',
      'Software Estimation',
      'JavaScript',
      'PostgreSQL',
      'MySQL',
      'Adobe Creative Suite',
      'Media Management',
      'Vue.js',
      'Angular.js',
      'Ractive.js'
    ]
  },
  {
    id: 'kosInteriorDesignInteriorDesigner',
    companyId: 'kosInteriorDesign',
    companyName: "Ko's Interior Design and Construction",
    title: 'Interior Designer',
    location: 'Toronto, Canada Area',
    startDate: fromZonedTime('2013-07-01', appTimeZone),
    endDate: fromZonedTime('2016-09-01', appTimeZone),
    skills: ['Adobe Creative Suite']
  }
]

export { jobEntries }
